[package]
name = "commands"
version = "0.1.0"
authors = ["Frederic Desgreniers <fredericdesgreniers@gmail.com>"]

[dependencies]
actix = "0.7.3"
irc = {path = "../irc"}
cold_data = {path = "../cold_data"}
futures = "*"
web_frontend = {path="../web_frontend"}
serde = "1.0.70"
serde_json = "1.0.24"
