[package]
name = "web_frontend"
version = "0.1.0"
authors = ["Frederic Desgreniers <fredericdesgreniers@gmail.com>"]

[dependencies]
actix = "0.7.2"
actix-web = "0.7.2"
tera = "0.11.9"
rand = "0.5.4"
env_logger = "0.5.11"