[package]
name = "irc"
version = "0.1.0"
authors = ["Frederic Desgreniers <fredericdesgreniers@gmail.com>"]

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
regex = "1.0.2"
lazy_static = "1.0.2"
actix = "0.7.3"